name: phone_data_sender
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info_plus: ^9.0.0
  battery_plus: ^6.2.1
  permission_handler: ^11.3.1
  flutter_background: ^1.3.0+1

  intl: ^0.19.0
  # hive no sql database
  hive: ^2.2.3
  # path
  path_provider: ^2.1.2
  # get it singleton
  get_it: ^7.6.7
  # async
  async: ^2.11.0
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.4
  # interceptor
  dio: ^5.4.1
  dio_retry_plus: ^2.0.6
  # chuck
  chuck_interceptor: ^2.1.0
  # box
  gap: ^3.0.1
  # pin put
  pinput: ^4.0.0
  # router
  go_router: ^13.2.0
  # svg render
  flutter_svg: ^2.0.10+1
  # url launchers
  url_launcher: ^6.2.5
  # dropdown
  dropdown_button2: ^2.3.9
  # package info
  package_info_plus: ^8.1.2
  # cached image
  cached_network_image: ^3.3.1
  # firebase
#  firebase_core: ^2.27.0
#  firebase_analytics: ^10.8.9
#  firebase_messaging: ^14.7.19
#  firebase_remote_config: ^4.3.17
  # local notification
  flutter_local_notifications: ^17.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
#  hive_generator: ^2.0.1
#  flutter_lints: ^3.0.1
#  build_runner: ^2.4.8
#  bloc_test: ^9.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/AppIcons.ttf

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
